export default {
  jobs: [
    "construction technician",
    "stonemason",
    "bricklayer",
    "roofer",
    "plasterer",
    "ceramist",
    "plumber",
    "pipefitter",
    "electrician",
    "house painter/decorator",
    "glazier",
    "carpenter",
    "flooring installer",
    "heavy equipment operator",
    "reinforcing ironworker",
    "structural ironworker",
  ],
  yearsOfExperience: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
  ],
} as const;
